name = "SymSpellChecker"
uuid = "bb1b64e9-0ccc-445c-80cb-5313b9f7dfe1"
authors = ["Andrey Oskin"]
version = "0.1.0"

[deps]
StringDistances = "88034a9c-02f8-509d-84a9-84ec65e18404"

[compat]
julia = "1.3"
StringDistances = "0.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
PkgBenchmark = "32113eaa-f34f-5b0d-bd6c-c81e245fc73d"

[targets]
test = ["Test"]
